spring:
  config:
    import: optional:file:.env.dev[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
