application:
  front-end-url: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG

spring:
  config:
    import: optional:file:.env.dev[.properties]

  jpa:
    show-sql: true
