package com.feponiel.swiftpass.domain.application.usecases.exceptions;

public enum DomainExceptionCode {
  ACTIVE_EVENT_DELETION_NOT_ALLOWED,
  EVENT_END_DATE_BEFORE_START_DATE,
  EVENT_ALREADY_ENDED,
  EVENT_NOT_FOUND,
  EVENT_SALES_CLOSED,
  INVALID_CURRENCY,
  INVALID_STRIPE_WEBHOOK,
  NO_FIELD_PROVIDED,
  REGISTRATION_NOT_FOUND,
  REGISTRATION_NOT_PAID,
  STRIPE_EVENT_DESERIALIZATION_FAILED,
  TICKET_NOT_FOUND,
  USER_NOT_FOUND
}
